#!/bin/sh
cd ..


echo 'checkout head'
git reset --hard

git submodule init
git submodule update

echo 'pwd'
echo `pwd`

echo 'set rvm'
source /usr/local/rvm/scripts/rvm
rvm use --create ree@excedent

echo 'deploy gems'
bundle install --deployment

echo 'rake db:migrate'
RAILS_ENV=production rake db:migrate cache:build 

echo 'restart server'
kill -HUP `cat tmp/pid/unicorn.pid`


