#!/bin/bash
cd ..

echo 'checkout head'
env -i git reset --hard

git submodule init
git submodule update

echo 'uh?'

echo 'set rvm'
source /usr/local/rvm/scripts/rvm
rvm use --create ree@excedent

echo 'deploy gems'
bundle install --deployment

echo 'rake db:migrate'
RAILS_ENV=production rake db:migrate cache:build 

echo 'restart server'
kill -HUP `cat tmp/pid/unicorn.pid`


